/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.michell.vendas.vr.views;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author michell-bento
 */
public class VendasMainForm extends javax.swing.JFrame {

    /**
     * Creates new form VendasMainForm
     */
    public VendasMainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/background.jpg"));
        Image image = icon.getImage();
        desktopPane = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(), this);
            }

        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuClient = new javax.swing.JMenuItem();
        menuProduct = new javax.swing.JMenuItem();
        menuPurchaseOrder = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VENDAS-VR");
        setExtendedState(6);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(103, 55));

        jMenu1.setForeground(new java.awt.Color(255, 153, 51));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vr-icon-32.png"))); // NOI18N
        jMenu1.setText("VR Software - Vendas");
        jMenu1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        menuClient.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        menuClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file.png"))); // NOI18N
        menuClient.setText("Clientes");
        menuClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientActionPerformed(evt);
            }
        });
        jMenu1.add(menuClient);

        menuProduct.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        menuProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Application-x-deb.svg.png"))); // NOI18N
        menuProduct.setText("Produtos");
        jMenu1.add(menuProduct);

        menuPurchaseOrder.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        menuPurchaseOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Application-x-deb.svg.png"))); // NOI18N
        menuPurchaseOrder.setText("Pedidos de compras");
        menuPurchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPurchaseOrderActionPerformed(evt);
            }
        });
        jMenu1.add(menuPurchaseOrder);
        jMenu1.add(jSeparator1);

        menuExit.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        menuExit.setForeground(new java.awt.Color(255, 153, 0));
        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit-icon-2.png"))); // NOI18N
        menuExit.setText("Sair");
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        setSize(new java.awt.Dimension(620, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuPurchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPurchaseOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPurchaseOrderActionPerformed

    private void menuClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientActionPerformed
        // TODO add your handling code here:
        RegisterCustomerForm formCustomer = new RegisterCustomerForm();
        desktopPane.add(formCustomer);
        formCustomer.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_menuClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendasMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuClient;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuProduct;
    private javax.swing.JMenuItem menuPurchaseOrder;
    // End of variables declaration//GEN-END:variables
}
